Repository Jimmy32767255/JimGrasscutterServerLauncher, pull requests merged in 2025-05, with the labels that each got.

#2 优化下载/设置界面
  JGSL/download_tab.py
  JGSL/settings_tab.py
Labels: enhancement

#3 更新编辑器配置
  JGSL/download_tab.py
  JGSL/settings_tab.py
Labels: enhancement, python

#4 修改了 todolist 中的提示并在下载页面中提示了功能不可用
  JGSL/download_tab.py
  todolist.md
Labels: documentation

#5 调整了集群管理页面的布局
  JGSL/cluster_tab.py
Labels: enhancement, python
